#! /usr/bin/bash

cat /etc/hosts | while read id dns noUse; do
    if [ "$id" == "::1" ]; then
        break
    elif [ "$id" == "127.0.0.1" ]; then
        continue
    fi
    cnt=0
    nslookup "$dns" 8.8.8.8 | while read text ip nouse; do
        if [ "$cnt" -eq 5 ]; then
            if [ "$id" != "$ip" ]; then
                echo "Bogus IP for $dns in /etc/hosts"
            fi
        fi
        ((cnt++))
    done
done

